import { query } from './db.js'

export async function initSalesSchema() {
  const statements = [
    `CREATE TABLE IF NOT EXISTS sales_recordings (id BIGINT AUTO_INCREMENT PRIMARY KEY, organization_id INT NOT NULL, user_id VARCHAR(64) NOT NULL, seller_label VARCHAR(128), scene VARCHAR(64), consent_confirmed TINYINT(1) NOT NULL DEFAULT 0, asset_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'uploaded', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_sales_recording_org (organization_id, created_at), INDEX idx_sales_recording_seller (organization_id, seller_label, scene)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS transcription_jobs (id BIGINT AUTO_INCREMENT PRIMARY KEY, recording_id BIGINT NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'queued', transcript JSON, provider VARCHAR(64), error_message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_transcription_recording (recording_id, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS sales_analyses (id BIGINT AUTO_INCREMENT PRIMARY KEY, recording_id BIGINT NOT NULL, scene VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'needs_review', score DECIMAL(5,2), level VARCHAR(32), skill_version VARCHAR(64), report JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_sales_analysis_recording (recording_id, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS sales_evidence (id BIGINT AUTO_INCREMENT PRIMARY KEY, analysis_id BIGINT NOT NULL, dimension VARCHAR(64), quote TEXT, start_seconds DECIMAL(10,2), end_seconds DECIMAL(10,2), severity VARCHAR(32), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_sales_evidence_analysis (analysis_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS training_tasks (id BIGINT AUTO_INCREMENT PRIMARY KEY, organization_id INT NOT NULL, analysis_id BIGINT NOT NULL, title VARCHAR(160) NOT NULL, content JSON, status VARCHAR(32) NOT NULL DEFAULT 'pending', due_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_training_task_org (organization_id, status), INDEX idx_training_task_analysis (analysis_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS sales_score_snapshots (id BIGINT AUTO_INCREMENT PRIMARY KEY, organization_id INT NOT NULL, seller_label VARCHAR(128), scene VARCHAR(64), score DECIMAL(5,2) NOT NULL, skill_version VARCHAR(64) NOT NULL, analysis_id BIGINT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_sales_snapshot (organization_id, seller_label, scene, skill_version, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`
  ]
  for (const statement of statements) await query(statement)
}
