<script setup>
import { onMounted, ref } from 'vue'
import { useOrganizationStore } from '@/stores/organization'
import { closeServiceAlert, createServiceProgram, getServiceRecommendations, listServiceAlerts, listServicePrograms } from '@/api/growth'
const organization = useOrganizationStore(); const programs = ref([]); const alerts = ref([]); const recommendations = ref([]); const busy = ref(false); const message = ref('')
const config = () => ({ headers: organization.headers() })
const programTypeText = { acquisition_sprint_30: '30天获客冲刺', growth_coaching_90: '90天标准增长陪跑', founder_advisor: '创始人增长顾问' }
const programStatusText = { pending: '待启动', active: '进行中', completed: '已完成', paused: '已暂停', cancelled: '已取消' }
const displayProgramType = value => programTypeText[value] || '定制服务计划'
const displayProgramStatus = value => programStatusText[value] || '状态待确认'
onMounted(async () => { await organization.load(); const [p, a, r] = await Promise.all([listServicePrograms(config()), listServiceAlerts(config()), getServiceRecommendations(config())]); programs.value = p.programs || []; alerts.value = a.alerts || []; recommendations.value = r.recommendations || [] })
async function create(type) { busy.value = true; try { const response = await createServiceProgram({ type, startDate: new Date().toISOString().slice(0, 10) }, config()); programs.value.unshift(response.program); message.value = '服务计划已建立，节点已生成' } catch (error) { message.value = '操作未完成，请稍后重试' } finally { busy.value = false } }
async function closeAlert(alert) { try { await closeServiceAlert(alert.id, config()); alerts.value = alerts.value.filter(item => item.id !== alert.id); message.value = '问题已关闭' } catch (error) { message.value = '操作未完成，请稍后重试' } }
</script>
<template><main class="page"><section class="hero"><span class="eyebrow">真人陪跑服务</span><h1>系统辅助整理，真人顾问确认与纠偏</h1><p>系统负责整理信息、提醒节点和提供复盘参考；真人顾问负责确认目标、复杂判断和执行纠偏。服务不承诺固定经营结果。</p></section><section v-if="alerts.length" class="history"><h2>待处理问题</h2><div v-for="alert in alerts" :key="alert.id" class="program"><b>{{ alert.title }}</b><p>{{ alert.detail || '需要顾问结合当前执行情况确认。' }}</p><button @click="closeAlert(alert)">标记已处理</button></div></section><section v-if="recommendations.length" class="history"><h2>当前建议</h2><div v-for="item in recommendations" :key="item.type || item.title" class="program"><b>{{ item.title }}</b><p>{{ item.reason || item.detail }}</p></div></section><section class="plans"><article><h2>30天获客冲刺</h2><p>适合目标明确，只解决获客问题的机构。</p><ul><li>启动诊断</li><li>第15天纠偏</li><li>第30天复盘</li></ul><button @click="create('acquisition_sprint_30')" :disabled="busy">建立服务计划</button></article><article class="featured"><b class="ribbon">当前主推</b><h2>90天标准增长陪跑</h2><p>跑通获客、优化成交并固化方法。</p><ul><li>启动＋30/60/90天节点</li><li>系统检查与异常触达</li><li>顾问介入复杂问题</li></ul><button @click="create('growth_coaching_90')" :disabled="busy">预约诊断</button></article><article><h2>创始人增长顾问</h2><p>处理课包、活动、人效、坪效等非标准问题。</p><ul><li>每两周深度沟通</li><li>创始人参与</li><li>明确服务边界</li></ul><button class="gold" @click="create('founder_advisor')" :disabled="busy">申请沟通</button></article></section><section class="history"><h2>我的服务计划</h2><p v-if="!programs.length">还没有已建立的服务计划。</p><div v-for="program in programs" :key="program.id" class="program">{{ displayProgramType(program.program_type) }} · {{ program.start_date }} · {{ displayProgramStatus(program.status) }}</div></section><p v-if="message" class="message">{{ message }}</p></main></template>
<style scoped>.page{min-height:100vh;padding:42px clamp(20px,5vw,64px);background:#f5f3ec;color:#17231c}.hero{max-width:1280px;margin:auto;padding:30px;border-radius:18px;background:linear-gradient(135deg,#173d2c,#285f44);color:#fff}.hero h1{font-size:32px;margin:12px 0}.hero p{color:#c7d8cc}.eyebrow{color:#f1cb79;font-size:11px;font-weight:800;letter-spacing:1px}.plans{max-width:1280px;margin:18px auto;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.plans article{position:relative;background:#fff;border:1px solid #dce2dc;border-radius:16px;padding:22px}.plans .featured{border:2px solid #d4a84f}.plans p,.plans li,.history p{color:#6b756f;font-size:13px;line-height:1.6}.plans button{border:0;border-radius:9px;background:#1e563a;color:#fff;padding:11px 14px;font-weight:700}.plans .gold{background:#dcae53;color:#34260c}.ribbon{position:absolute;right:14px;top:14px;color:#745719;background:#f2d493;border-radius:99px;padding:4px 8px;font-size:10px}.history{max-width:1280px;margin:30px auto}.program{background:#fff;border:1px solid #dce2dc;border-radius:10px;padding:13px;margin-top:8px}.alert,.message{max-width:1280px;margin:16px auto;color:#8b681e}@media(max-width:800px){.plans{display:block}.plans article{margin-top:12px}}
</style>
